# Generated by Django 4.1.4 on 2022-12-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
